spring:
  datasource:
    url: jdbc:postgresql://dpg-d7abnaeuk2gs73cbbbi0-a.oregon-postgres.render.com/paquetrack_shipment_db
    username: paquetrack_shipment_db_user
    password: 2mdsDBX6vRHC2c7SxT2MhPjKni6dH5aQ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:shrimp.rmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USERNAME:edjhxutz}
    password: ${RABBITMQ_PASSWORD:ZFLZoeGFGN2Xh73jXifehAZP31gkyBt7}
    virtual-host: ${RABBITMQ_VHOST:edjhxutz}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}
    listener:
      simple:
        default-requeue-rejected: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    "[com.paquetrack]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.springframework.amqp]": DEBUG