spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paquetrack_shipment}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:shrimp.rmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USERNAME:edjhxutz}
    password: ${RABBITMQ_PASSWORD:}
    virtual-host: ${RABBITMQ_VHOST:edjhxutz}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}
    listener:
      simple:
        default-requeue-rejected: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    "[com.paquetrack]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.springframework.amqp]": DEBUG